import {useEffect,useRef,useState,type ReactNode} from "react";

const projects=[
 {no:"01",name:"THE APPROACH",meta:"Arrival / 2026",image:"https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=2200&q=85"},
 {no:"02",name:"THE FORM",meta:"Architecture / 2026",image:"https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=2200&q=85"},
 {no:"03",name:"THE INTERIOR",meta:"Living / 2026",image:"https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=2200&q=85"}
];
function Reveal({children,className=""}:{children:ReactNode;className?:string}){const r=useRef<HTMLDivElement>(null);const[v,setV]=useState(false);useEffect(()=>{const o=new IntersectionObserver(([e])=>e.isIntersecting&&setV(true),{threshold:.12});if(r.current)o.observe(r.current);return()=>o.disconnect()},[]);return <div ref={r} className={className+" reveal "+(v?"visible":"")}>{children}</div>}
export default function App(){
 const [active,setActive]=useState(0); const hero=useRef<HTMLDivElement>(null);
 useEffect(()=>{const on=()=>{const y=window.scrollY;document.documentElement.style.setProperty("--scroll",String(Math.min(y/900,1)));};window.addEventListener("scroll",on,{passive:true});on();return()=>window.removeEventListener("scroll",on)},[]);
 return <main>
  <div className="cursor"/>
  <header className="nav"><a className="logo" href="#">MONUMENT<span>®</span></a><nav><a href="#residence">Residence</a><a href="#architecture">Architecture</a><a href="#details">Details</a></nav><a className="menu" href="#contact">Inquire <b>↗</b></a></header>
  <section className="hero" ref={hero}><img src="https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=2600&q=90"/><div className="heroShade"/><div className="coordinates">31° 28' 14.2&quot; N &nbsp; / &nbsp; 74° 20' 03.8&quot; E</div><div className="heroTitle"><p>PRIVATE RESIDENCE · LAHORE · 2026</p><h1>A HOUSE<br/><i>BUILT AROUND</i><br/>SILENCE.</h1><a href="#residence">Explore residence <b>↓</b></a></div><div className="heroBottom"><span>MONUMENT / 001</span><span>SCROLL TO ENTER</span></div></section>
  <section className="statement" id="residence"><div className="statementIndex">01 — THE IDEA</div><Reveal><p className="kicker">MONUMENTAL, NOT OSTENTATIOUS</p><h2>Architecture<br/><i>with nothing</i><br/>to prove.</h2><p className="lead">A private residence conceived as a quiet composition of stone, light and proportion. Every room is measured against the landscape; every material chosen to age with grace.</p></Reveal></section>
  <section className="sequence" id="architecture"><div className="sequenceSticky"><div className="seqImage"><img src={projects[active].image}/><div className="seqShade"/></div><div className="seqCopy"><span>0{active+1}</span><h2>{projects[active].name}</h2><p>{projects[active].meta}</p></div><div className="seqNav">{projects.map((p,i)=><button key={p.no} onClick={()=>setActive(i)} className={active===i?"on":""}><span>{p.no}</span>{p.name}</button>)}</div></div></section>
  <section className="plan"><Reveal><div className="planTop"><span>02 — SPATIAL LOGIC</span><span>1,240 M² / 13,347 FT²</span></div><div className="planVisual"><div className="floor"><span>COURTYARD</span><span>LIVING</span><span>DINING</span><span>PRIVATE</span><span>POOL</span></div></div><div className="planText"><h2>Spaces that<br/><i>frame life.</i></h2><p>Long axial views connect the house from entrance to garden. Light enters from courtyards rather than windows alone, creating a sequence of changing atmospheres throughout the day.</p></div></Reveal></section>
  <section className="materials"><div className="materialImage"><img src="https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?auto=format&fit=crop&w=2200&q=85"/></div><div className="materialCopy"><p className="kicker">03 — MATERIAL PALETTE</p><h2>Stone.<br/>Oak.<br/><i>Shadow.</i></h2><p>Travertine underfoot. Smoked oak at touch. Patinated bronze where hand meets architecture. Nothing polished beyond what time can improve.</p><div className="materialList"><span>01 / TRAVERTINE</span><span>02 / SMOKED OAK</span><span>03 / PATINATED BRONZE</span><span>04 / NATURAL LINEN</span></div></div></section>
  <section className="numbers"><div><span>LAND</span><strong>2,800</strong><small>M²</small></div><div><span>RESIDENCE</span><strong>1,240</strong><small>M²</small></div><div><span>COURTYARD</span><strong>04</strong><small>LIGHT WELLS</small></div><div><span>ORIENTATION</span><strong>360°</strong><small>GARDEN VIEWS</small></div></section>
  <section className="gallery"><Reveal><p className="kicker">04 — THE RESIDENCE</p><div className="galleryGrid"><img src="https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?auto=format&fit=crop&w=1800&q=85"/><img src="https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=1800&q=85"/><img src="https://images.unsplash.com/photo-1600210491892-03d54c0aaf87?auto=format&fit=crop&w=1800&q=85"/></div></Reveal></section>
  <section className="contact" id="contact"><div><p>MONUMENT / PRIVATE RESIDENCE 001</p><h2>Come<br/><i>inside.</i></h2></div><a href="mailto:studio@monument.example">Request private viewing <b>↗</b></a></section>
  <footer><span>MONUMENT®</span><span>LAHORE / PAKISTAN</span><span>© 2026</span></footer>
 </main>
}